### ISSUE TITLE
⚡Slider 컴포넌트 개발

### ISSUE THREAD

**Issue by springkjw** [osamhack2022/WEB_AI_MILIROUTINE_MILIROUTINE#17]
- 홈 화면에 루틴 아이템을 Slider 형식으로 보여줄 컴포넌트 개발 필요.
- 라이브러리를 사용해도 되지만, TailwindCSS를 이용하여 자체 개발할 예정.
- 개발 Scope이 모바일은 포함되어 있지않기 때문에 웹에서 동작하는 것만 생각하기.

**Comment by springkjw** [comment]
해당 Slider에 대해서 다음과 같은 결정사항이 필요합니다.

- AutoPlay 기능이 들어가는가?
- AutoPlay가 들어간다면 Interval 은 몇 초로 하는게 좋을까?
- 맨 끝 아이템까지 도달한 상태에서 Arrow 를 클릭하면 어떻게 Action하는가?(처음으로 다시? or 첫 아이템이 이어서 나오는지?)

**Comment by yoopark** [comment]
제가 구상했던 건 다음과 같습니다. 
- AutoPlay가 들어가지 않습니다. (Arrow를 눌러야만 움직입니다)
- 1등 요소를 가장 왼쪽에 놓고 시작하며, 맨 끝 아이템 다음에 처음 으로 다시 돌아오도록 하여 추천이 계속되는 느낌을 주도록 합니다. 

Autoplay가 Main Page에 두개나 들어있으면 약간 어지러울 거 같아서 그렇게 생각했는데, 혹시 다른 생각 있으실까요??

**Comment by springkjw** [comment]
> 제가 구상했던 건 다음과 같습니다.
> 
> * AutoPlay가 들어가지 않습니다. (Arrow를 눌러야만 움직입니다)
> * 1등 요소를 가장 왼쪽에 놓고 시작하며, 맨 끝 아이템 다음에 처음 으로 다시 돌아오도록 하여 추천이 계속되는 느낌을 주도록 합니다.
> 
> Autoplay가 Main Page에 두개나 들어있으면 약간 어지러울 거 같아서 그렇게 생각했는데, 혹시 다른 생각 있으실까요??

괜찮을거 같아요.

**Comment by springkjw** [comment]
- [x] #20
