### ISSUE TITLE
signup/more 페이지 작업

### ISSUE THREAD

**Issue by silverttthin** [osamhack2022/WEB_AI_MILIROUTINE_MILIROUTINE#18]
- [x] #22
- [x] Category true/false 컴포넌트 제작
- [x] PreferMiliroutineTrue/False 컴포넌트 제작
- [x] signup/more 페이지 구현 돌입
- [x] Category True/False 두개 만들어 둔거 하나로 통합하기
- [x] PreferMiliroutine True/False 두개 만들어 둔거 하나로 통합하기
- [ ] svg 줄넘김 상황 및 해결못한 레이아웃 문제 해결 및 최종 완성

파이팅!

**Comment by springkjw** [comment]
기획안을 보니 signup 이랑 signup/more이랑 사실상 같은 flow라 같은 `SignupPage` 내에서 개발하면 될 것 같습니다.
