### ISSUE TITLE
기획/디자인 단순화 논의

### ISSUE THREAD

**Issue by yoopark** [osamhack2022/WEB_AI_MILIROUTINE_MILIROUTINE#4]
처음에는 일단 간단하지만 작동하도록 만들라는 멘토님의 의견을 반영하여, 구현을 미룰 부분에 대하여 생각해보았습니다. 한번 보시고 의견을 댓글로 적어주시면 감사하겠습니다. 

1. 반응형 지원 → 보류
2. [카테고리별 인기] → 일단은 페이지 삭제
3. [기간별 인기] → 주간, 월간 나누는 의미 없을 듯. 그냥 전체 하나만 보여주도록
    1. 1, 2, 3위만 다르게 UI하는 것 → 보류
    2. 유튜브처럼 처음 8개만 보여주고 아래로 스크롤하면 계속 나타나도록
4. 인증 방법 중 [인증 예시 사진] → 보류
5. [밀리루틴 게시판] 기능 → 보류
    1. [밀리루틴 게시판] 삭제에 따른 GNB [알림] 삭제
6. [추천] 탭에서 [새로운 밀리루틴에도 도전해보세요] 기능 → 보류
    1. 추천은 Main Page 최상단으로 옮기고, 10~15개만 찾아서 보여주는 걸로. 
7. [추천] 탭에서 운영진에서 [큐레이션]으로 추천하는 기능 → 보류
8. 가입자수 통계 → 어차피 통계가 안 날 듯
9. 회원가입 시 유효성 검사, 유효성 검사 UI → 보류
10. Naver, Google 로그인 → 보류
11. 실명, 군 구분, 전역일자 등 없어도 되는 문항 삭제
    1. /signup 페이지에서 아이디, 비밀번호, 닉네임만 정하고 중복 검사
12. /signup/more 페이지에서 관심 카테고리 선택 + 넷플릭스처럼 밀리루틴 랜덤으로 제목만 띄워서 체크하도록 하는 란 신설 ← 멘토님 AI쪽 의견 반영
13. [나의 밀리루틴] 중 [북마크한 밀리루틴] 삭제
    1. [좋아요한 밀리루틴]은 일단 남김

가장 중요한 기능이 무엇일지 생각해보았고, 일단 과감하게 빼보았습니다
- [Figma 링크](https://www.figma.com/file/2TPzteo46E4nRDr6Fu7QQd/%EA%B8%B0%ED%9A%8D%EC%84%9C?node-id=272%3A1878)

링크로 들어오시면 현재 수정중인 Simple 버전의 디자인을 보실 수 있습니다. 
보시고 꼭 의견 남겨주세요!

**Comment by silverttthin** [comment]
저는 매우 좋은 의견이라 생각합니다. 일단 작고 필수적인 요소들 먼저 완성시키면서 프로젝트 진행하는게 안전할 것 같습니다. 구현해 나가면서 어느정도 여유가 생겼을 때 상단에 보류해둔 것들 중에서 의미있는 부가기능들 선별해서 업데이트하는게 좋을 것 같습니다. 
그리고 수정된 피그마 보니 !isLogin 메인페이지에 AI 추천 밀리루틴 탭이 있던데 로그인이 안돼있어 사용자 데이터가 없는 상태에서 AI가 추천할 수 있는지 질문하고 싶습니다.

**Comment by yoopark** [comment]
> 저는 매우 좋은 의견이라 생각합니다. 일단 작고 필수적인 요소들 먼저 완성시키면서 프로젝트 진행하는게 안전할 것 같습니다. 구현해 나가면서 어느정도 여유가 생겼을 때 상단에 보류해둔 것들 중에서 의미있는 부가기능들 선별해서 업데이트하는게 좋을 것 같습니다. 그리고 수정된 피그마 보니 !isLogin 메인페이지에 AI 추천 밀리루틴 탭이 있던데 로그인이 안돼있어 사용자 데이터가 없는 상태에서 AI가 추천할 수 있는지 질문하고 싶습니다.

넵 저도 생각했는데, 인기 순 풀을 좀 크게 잡고 그 중에 랜덤으로 나오도록 하면 괜찮을 것 같습니다!

**Comment by minchan02** [comment]
/signup/more 쪽 페이지는 간단하게 작성했습니다. 
나중에 AI부분 완성되면 그때 구현하겠습니다.

그리고 Naver,Google 로그인 쪽도 일단 다른 큰 기능들 완성될 때 까지 보류하겠습니다.

**Comment by yoopark** [comment]
F2F2F2 -> D9D9D9 로 색깔 변경 했습니다. 
Mac 환경에서 볼 때는 F2가 D9 색깔이었는데, 사지방에서 보니까 그냥 흰색이더라구요... 모두들 색깔이 너무 흰 디자인안을 보고 있었군요!!!!
