### ISSUE TITLE
(BE) 작업 진행사항 2022.10.2

### ISSUE THREAD

**Issue by minchan02** [osamhack2022/WEB_AI_MILIROUTINE_MILIROUTINE#6]
<완료>
- router 분리
- 로그인, 회원가입 기능 구현
- DB 연결 (나중에 VM환경 받으면 따로 또 연결)

<진행>
- routine개설 및 DB연결

**Comment by minchan02** [comment]
#5

**Comment by yoopark** [comment]
넵! VM 며칠 전에 신청해서, 아마 이번주 수요일 중에 받을 수 있을 것 같아요..! 제가 잘 몰라서 이제야 신청했는데 곧 사용하실 수 있을 겁니다!

**Comment by minchan02** [comment]
넵 알겠습니다!
