### ISSUE TITLE
(FE) 개발 전 진행상황

### ISSUE THREAD

**Issue by silverttthin** [osamhack2022/WEB_AI_MILIROUTINE_MILIROUTINE#7]
디자인 확정 이전까지 FE에서 사용할 react, redux, react-query 복습 및 일부 내용 추가 필기하였습니다.
최근 사지방에서 코드스페이스가 잘 작동하지 않아 일단 구름IDE에서 공부하였으며 필기 내용은 하단 notion 링크 첨부하겠습니다.
https://band-baseball-d12.notion.site/bdcfe3cb724a4002bed650b583bbf37c

이후 내일 일부 내용이 생략되어 심플하게 바뀐 디자인 확정 이후 남은 시간은 전부 개발 및 추가 내용공부에 할애할 예정입니다

**Comment by yoopark** [comment]
굿! 좋습니다~
<https://nomadcoders.co/react-for-beginners/lectures/3286>
노마드코더의 React 기초 강의도 좋더라구요. Typescript가 나오진 않지만 useState, useEffect, react-router에 대해 쉽게 알려줍니다.
